import { useState, useEffect } from 'react'

export default function ExtraResources() {
  const [picks, setPicks] = useState(null)
  const [earnings, setEarnings] = useState(null)
  const [loadingPicks, setLoadingPicks] = useState(true)
  const [loadingEarnings, setLoadingEarnings] = useState(true)

  useEffect(() => {
    const fetchPicks = async () => {
      try {
        const res = await fetch('/api/daily-picks')
        const data = await res.json()
        setPicks(data)
      } catch {
        setPicks({ picks: [], error: 'Failed to load picks' })
      } finally {
        setLoadingPicks(false)
      }
    }

    const fetchEarnings = async () => {
      try {
        const res = await fetch('/api/earnings-calendar')
        const data = await res.json()
        setEarnings(data)
      } catch {
        setEarnings({ earnings: [], error: 'Failed to load earnings' })
      } finally {
        setLoadingEarnings(false)
      }
    }

    fetchPicks()
    fetchEarnings()
  }, [])

  const signalColor = (signal) => {
    if (signal === 'Strong Buy') return 'text-green-400 bg-green-500/10 border-green-500/30'
    if (signal === 'Buy') return 'text-green-500 bg-green-500/5 border-green-500/20'
    if (signal === 'Strong Sell') return 'text-red-400 bg-red-500/10 border-red-500/30'
    if (signal === 'Sell') return 'text-red-500 bg-red-500/5 border-red-500/20'
    return 'text-neutral-400 bg-neutral-500/5 border-neutral-500/20'
  }

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-white mb-2">Extra Resources</h1>
        <p className="text-neutral-400">
          Daily top picks generated by our technical analysis engine, plus upcoming major earnings.
        </p>
      </div>

      {/* Top 15 Daily Picks */}
      <div className="bg-black border border-neutral-700 rounded-xl p-6 mb-8">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h2 className="text-xl font-bold text-white">Top 15 Picks of the Day</h2>
            <p className="text-neutral-500 text-sm mt-1">
              Ranked by RSI, momentum, volatility, and trend signals
            </p>
          </div>
          {picks?.generated_at && (
            <span className="text-neutral-600 text-xs">
              Updated: {new Date(picks.generated_at).toLocaleTimeString()}
            </span>
          )}
        </div>

        {loadingPicks ? (
          <div className="text-center py-12">
            <div className="inline-block w-8 h-8 border-2 border-neutral-700 border-t-white rounded-full animate-spin"></div>
            <p className="text-neutral-500 mt-3">Analyzing stocks... This takes a moment.</p>
          </div>
        ) : picks?.picks?.length > 0 ? (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-neutral-800">
                  <th className="text-left text-neutral-500 text-xs font-medium py-3 px-2">#</th>
                  <th className="text-left text-neutral-500 text-xs font-medium py-3 px-2">SYMBOL</th>
                  <th className="text-right text-neutral-500 text-xs font-medium py-3 px-2">PRICE</th>
                  <th className="text-right text-neutral-500 text-xs font-medium py-3 px-2">RSI</th>
                  <th className="text-right text-neutral-500 text-xs font-medium py-3 px-2">20D MOM</th>
                  <th className="text-right text-neutral-500 text-xs font-medium py-3 px-2">30D UP%</th>
                  <th className="text-center text-neutral-500 text-xs font-medium py-3 px-2">SIGNAL</th>
                  <th className="text-left text-neutral-500 text-xs font-medium py-3 px-2">REASONS</th>
                </tr>
              </thead>
              <tbody>
                {picks.picks.map((pick) => (
                  <tr key={pick.symbol} className="border-b border-neutral-900 hover:bg-neutral-900/50 transition-colors">
                    <td className="py-3 px-2">
                      <span className={`text-sm font-bold ${
                        pick.rank <= 3 ? 'text-white' : 'text-neutral-500'
                      }`}>
                        {pick.rank}
                      </span>
                    </td>
                    <td className="py-3 px-2">
                      <span className="text-white font-mono font-bold text-sm">{pick.symbol}</span>
                    </td>
                    <td className="py-3 px-2 text-right">
                      <span className="text-white font-mono text-sm">${pick.price}</span>
                    </td>
                    <td className="py-3 px-2 text-right">
                      <span className={`font-mono text-sm ${
                        pick.rsi < 30 ? 'text-green-500' :
                        pick.rsi > 70 ? 'text-red-500' : 'text-neutral-300'
                      }`}>
                        {pick.rsi}
                      </span>
                    </td>
                    <td className="py-3 px-2 text-right">
                      <span className={`font-mono text-sm ${
                        pick.momentum_20d >= 0 ? 'text-green-500' : 'text-red-500'
                      }`}>
                        {pick.momentum_20d >= 0 ? '+' : ''}{pick.momentum_20d}%
                      </span>
                    </td>
                    <td className="py-3 px-2 text-right">
                      <span className={`font-mono text-sm ${
                        pick.prob_up_30d >= 50 ? 'text-green-500' : 'text-red-500'
                      }`}>
                        {pick.prob_up_30d}%
                      </span>
                    </td>
                    <td className="py-3 px-2 text-center">
                      <span className={`inline-block px-2 py-1 rounded text-xs font-bold border ${signalColor(pick.signal)}`}>
                        {pick.signal}
                      </span>
                    </td>
                    <td className="py-3 px-2">
                      <div className="flex flex-wrap gap-1">
                        {pick.reasons.map((r, i) => (
                          <span key={i} className="text-neutral-500 text-xs">{r}{i < pick.reasons.length - 1 ? ' · ' : ''}</span>
                        ))}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <p className="text-neutral-500 text-center py-8">No picks available right now. Check back later.</p>
        )}

        {picks?.total_analyzed > 0 && (
          <p className="text-neutral-600 text-xs mt-4">
            Analyzed {picks.total_analyzed} stocks to find the top 15. Rankings based on RSI, momentum, volatility, and trend.
          </p>
        )}
      </div>

      {/* Earnings Calendar */}
      <div className="bg-black border border-neutral-700 rounded-xl p-6">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h2 className="text-xl font-bold text-white">Upcoming Earnings This Week</h2>
            <p className="text-neutral-500 text-sm mt-1">
              Major companies reporting earnings in the next 7 days
            </p>
          </div>
          {earnings?.week_start && (
            <span className="text-neutral-600 text-xs">
              {earnings.week_start} to {earnings.week_end}
            </span>
          )}
        </div>

        {loadingEarnings ? (
          <div className="text-center py-12">
            <div className="inline-block w-8 h-8 border-2 border-neutral-700 border-t-white rounded-full animate-spin"></div>
            <p className="text-neutral-500 mt-3">Loading earnings calendar...</p>
          </div>
        ) : earnings?.earnings?.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {earnings.earnings.map((e) => (
              <div key={e.symbol} className="bg-neutral-900 border border-neutral-800 rounded-lg p-4 hover:border-neutral-600 transition-colors">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-white font-mono font-bold text-lg">{e.symbol}</span>
                  <span className="text-neutral-400 text-sm">{e.day_of_week}</span>
                </div>
                <p className="text-neutral-500 text-sm mb-3">{e.date}</p>
                <div className="space-y-1">
                  {e.eps_estimate && (
                    <div className="flex justify-between">
                      <span className="text-neutral-500 text-xs">EPS Estimate</span>
                      <span className="text-white text-xs font-mono">${e.eps_estimate}</span>
                    </div>
                  )}
                  {e.revenue_estimate && (
                    <div className="flex justify-between">
                      <span className="text-neutral-500 text-xs">Revenue Est.</span>
                      <span className="text-white text-xs font-mono">
                        ${(e.revenue_estimate / 1e9).toFixed(1)}B
                      </span>
                    </div>
                  )}
                  {!e.eps_estimate && !e.revenue_estimate && (
                    <span className="text-neutral-600 text-xs">Estimates pending</span>
                  )}
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="text-center py-8">
            <p className="text-neutral-400 mb-2">No major earnings scheduled this week.</p>
            <p className="text-neutral-600 text-sm">Check back during earnings season (typically January, April, July, October).</p>
          </div>
        )}
      </div>

      <p className="text-neutral-600 text-xs mt-6 text-center italic">
        All data from Yahoo Finance. Picks are generated by technical analysis algorithms and are NOT financial advice.
        Always do your own research before investing.
      </p>
    </div>
  )
}
